name: CI

on:
  pull_request:
  push:
    branches: [main]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ruby ## latest MRI
          bundler-cache: true
      - name: Run Linter
        run: bin/ci-lint

  rspec:
    runs-on: ubuntu-latest
    env:
      FARADAY_VERSION: ${{ matrix.faraday }}
    strategy:
      fail-fast: false
      matrix:
        ruby: ["3.0", "3.1", "3.2", "3.3"]
        faraday: ["~> 2.0"]
    steps:
      - uses: actions/checkout@v4
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - name: Run Tests
        run: bin/ci-test
